import Header from "./header";
import Head from "next/head";
import styles from "../styles/MainContainer.module.css"
import Navbar from "./Navbar";


const MainContainer = ({children,painters}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Painting Life</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon"
              href="https://artquid-art.imgix.net/12/146/824025.510017934.1.o155330513.jpg?fit=max&w=575&border=0,00FF0000"/>
      </Head>
      <Header painters={painters} />
      <div>
        {children}
      </div>
    </div>

  )
}

export default MainContainer